# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  baseProject: 'Lett.Extensions/Lett.Extensions.csproj'           # 主体项目文件
  testProject: 'Lett.Extensions.Test/Lett.Extensions.Test.csproj' # 单元测试项目文件
  buildConfiguration: 'Release'                                   # 编译配置
  NuGetKey: '$(NuGetApiKey)'
  Major: '0'
  Minor: '0'
  Patch: '1'

steps:
- task: DotNetCoreCLI@2
  displayName: 还原nuget包
  inputs:
    command: restore
    projects: '$(baseProject)'

- task: DotNetCoreCLI@2
  displayName: 开始编译
  inputs:
    command: build
    projects: '$(baseProject)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 单元测试
  inputs:
    command: test
    projects: '$(testProject)'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishTestResults@2
  displayName: 发布测试报告
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: NuGetCommand@2
  inputs:
    command: pack
    versioningScheme: byBuildNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: $(NuGetKey)
    versioningScheme: byPrereleaseNumber