trigger: none

pool:
  name: Hosted Windows 2019 with VS2019

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  BaseProject: '**/Lett.Extensions.csproj'
  TestProject: '**/Lett.Extensions.Test.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: '还原NuGet包'
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: '编译'
    inputs:
      projects: '$(BaseProject)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: '测试'
    inputs:
      command: test
      projects: '$(TestProject)'
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

  - task: DotNetCoreCLI@2
    displayName: '打包'
    inputs:
      command: pack
      projects: '$(BaseProject)'
      arguments: '--configuration $(BuildConfiguration)'
      versioningScheme: byEnvVar
      versionEnvVar: packVersion

  - task: NuGetCommand@2
    displayName: 'NuGet 发布'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: myget.org
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
