trigger:
  branches:
    include:
      - master
      - develop
      - release/*
  paths:
    exclude:
      - README.md
      - docs/*
      - docs/*.md

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2
  displayName: '安装 .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.2.203
    installationPath: $(Agent.ToolsDirectory)/dotnet
- bash: |
    chmod +x ./build.sh
    ./build.sh
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: Linux 平台 执行 cake
- bash: |
    chmod +x ./build.sh
    ./build.sh
  condition: in( variables['Agent.OS'], 'Darwin' )
  displayName: MacOS 平台 执行 cake
- powershell: |
    ./build.ps1
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Windows 平台 执行 cake

# variables:
#   BuildConfiguration: 'Release'
#   BuildPlatform: 'any cpu'
#   BaseProject: '**/Lett.Extensions.csproj'
#   TestProject: '**/Lett.Extensions.Test.csproj'

# steps:
#   - task: DotNetCoreCLI@2
#     displayName: '还原NuGet包'
#     inputs:
#       command: restore
#       projects: '**/*.csproj'

#   - task: DotNetCoreCLI@2
#     displayName: '编译'
#     inputs:
#       projects: '$(BaseProject)'
#       arguments: '--configuration $(BuildConfiguration)'

#   - task: DotNetCoreCLI@2
#     displayName: '测试'
#     inputs:
#       command: test
#       projects: '$(TestProject)'
#       arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
