trigger:
  branches:
    include:
      - master
      - develop
      - release/*
  paths:
    exclude:
      - README.md
      - docs/*

variables:
  dotnetVersion: 2.2.300
  nugetPackPath: './nugetPacks'
  TestProject: '**/Lett.Extensions.Test.csproj'

jobs:
  # Linux (Docker - ubuntu-16.04)
  - job: Docker_ubuntu_1604
    condition: eq(variables['isPushNuget'], 'false')
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - bash: |
          chmod +x ./build.sh
          ./build.sh --target=azure
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        displayName: 执行 cake - Linux (Docker - ubuntu-16.04)
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  # MacOS (Docker - macOS-10.14)
  - job: Docker_MacOS_1014
    condition: eq(variables['isPushNuget'], 'false')
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - bash: |
          chmod +x ./build.sh
          ./build.sh --target=azure
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        displayName: 执行 cake - MacOS (Docker - macOS-10.14)
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  # Windows (Docker - windows-2019)
  - job: Docker_Windows_2019
    condition: eq(variables['isPushNuget'], 'false')
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 --target=azure
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 执行 cake - Windows (Docker - windows-2019)
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  # Windows (Windows 2019 with VS2019)
  - job: Hosted_Windows_2019
    condition: eq(variables['isPushNuget'], 'false')
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 --target=azure
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 执行 cake - Hosted (Windows 2019 with VS2019)
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  # Windows (Windows 2019 with VS2019)
  - job: Hosted_VS2017
    condition: eq(variables['isPushNuget'], 'false')
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 --target=azure
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: 执行 cake - Hosted (Hosted_VS2017)
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
  # Build Nuget Package
  - job: Build_NuGet_Package
    condition: eq(variables['isPushNuget'], 'true')
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: UseDotNet@2
        displayName: '安装 .NET Core sdk'
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 --target=azure --packVer=$(packVersion)
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
        displayName: Windows (Windows 2019 with VS2019) 平台 执行 cake pack
      - task: DotNetCoreCLI@2
        displayName: '测试'
        inputs:
          command: test
          projects: '$(TestProject)'
          arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
      - task: NuGetCommand@2
        displayName: 'NuGet 发布'
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: nuget.org
          packagesToPush: '$(nugetPackPath)/**/*.nupkg;$(nugetPackPath)/**/*.symbols.nupkg'
      - task: NuGetCommand@2
        displayName: 'MyGet 发布'
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: myget.org
          packagesToPush: '$(nugetPackPath)/**/*.nupkg;$(nugetPackPath)/**/*.symbols.nupkg'
