trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  BaseProject: '**/Lett.Extensions.csproj'
  TestProject: '**/Lett.Extensions.Test.csproj'
  Major: '0'
  Minor: '1'

steps:
- script: 'echo $(build.SourceLabel)'
- script: 'echo $(build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: '还原NuGet包'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: '编译'
  inputs:
    projects: '$(BaseProject)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '测试'
  inputs:
    command: test
    projects: '$(TestProject)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '打包'
  inputs:
    command: pack
    projects: '$(BaseProject)'
    arguments: '--configuration $(BuildConfiguration)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'

- task: NuGetCommand@2
  displayName: 'NuGet 发布'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
    packagesToPush: '**/*.nupkg;!**/*.symbols.nupkg'