trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  BaseProject: '**/Lett.Extensions.csproj'
  TestProject: '**/Lett.Extensions.Test.csproj'
  envVar: '1.0.0-RC'

steps:
- task: DotNetCoreCLI@2
  displayName: '还原NuGet包'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: '编译'
  inputs:
    projects: '$(BaseProject)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '测试'
  inputs:
    command: test
    projects: '$(TestProject)'
    arguments: '--configuration $(BuildConfiguration)'
  
# - task: PublishTestResults@2
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '**/*.trx'


