name: MyCI

on: 
  push:
    branches:
    - master
    - releases/*
  pull_request:  # Specify a second event with pattern matching
    branches:
    - master

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
